language: ruby
rvm:
  - 2.0.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtag1-dev mpd ffmpeg libavahi-compat-libdnssd-dev avahi-discover avahi-utils
before_script:
  - mysql -e 'create database play_test;'
  - bundle exec rake db:migrate
