language: ruby
rvm:
  - 2.0.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtag1-dev mpd mpc ffmpeg
before_script:
  - mv test/play.yml config
  - mysql -e 'create database play_test;'
  - bundle exec rake db:migrate
